### ISSUE TITLE
How to get the 'training.pt' file or make it by myself?

### ISSUE THREAD

**Issue by Watebear** [jmdbsa0012/AMTNN#1]
Hello researcher. I tried to run your code but it failed to load the file 'data/mnist/processed/training.pt'.
Would you please help me, upload the file or offer methods to make it .
Thank you.

**Comment by cjshui** [comment]
HI, 
The Mnist is the standard digit dataset. You can use the torchvision data loader to get it.

https://pytorch.org/docs/stable/torchvision/datasets.html
